register falta configurar correo de envio- home acabado
4GeeksAcademy/resuelveYa-app pull request #12
Opened 2024-09-13 18:15 UTC by Kevin962022

2024-09-13 21:58 UTC, erickact approved these changes

2024-09-13 22:07 UTC, erickact requested changes
change your code please (cors not imported)

2024-09-13 22:14 UTC, MaguiSanchez requested changes
CORS no imported:
from flask_cors import CORS
# Allow CORS requests to this API
CORS(api)

2024-09-14 14:30 UTC, Amat98 approved these changes

2024-09-15 00:09 UTC, Amat98 approved these changes

2024-09-15 00:17 UTC, MaguiSanchez approved these changes

2024-09-15 00:41 UTC, erickact approved these changes

2024-09-15 00:46 UTC, merged